language: generic
dist: xenial

jobs:
  include:
    - stage: deploy
      if: branch = master
      install:
        - git clone https://github.com/gohugoio/hugo.git
        - cd hugo
        - go install --tags extended
      script:
        - hugo -b https://cookieshake.blog/
      deploy:
        provider: surge
        project: ./public/
        domain: cookieshake.blog
        skip_cleanup: true





