language: generic
dist: xenial

jobs:
  include:
    - stage: deploy
      if: branch = master
      install:
        - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.57.1/hugo_extended_0.57.1_Linux-64bit.deb
        - sudo dpkg -i /tmp/hugo.deb
        - npm install --global surge
      script:
        - hugo
      after_success:
        - surge ./public cookieshake.blog





